dist: trusty

language: rust

cache: cargo

addons:
  apt:
    packages:
      - libgtk-3-dev

os:
  - linux
  - osx

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true